development:
 adapter: postgresql
 encoding: unicode
 database: db_tom_dev
 username: luksolek
 password: lomtjjzls1
 host: localhost
 pool: 5

test:
 adapter: postgresql
 encoding: unicode
 database: db_tom_test
 username: luksolek
 password: lomtjjzls1
 host: localhost
 pool: 5
